apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: notes-app

resources:
  - namespace.yaml
  - postgres-secrets.yaml
  - postgres-pvc.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - ingress.yaml
  - backend-hpa.yaml
  - frontend-hpa.yaml

commonLabels:
  app.kubernetes.io/name: notes-app
  app.kubernetes.io/part-of: notes-application
  managed-by: argocd
